### ISSUE TITLE
Use with mocha & webextension-polyfill

### ISSUE THREAD

**Issue by NicolasWanteeed** [Lusito/mockzilla-webextension#1]
Hi there 👋

This looks quite promising.
I'm quite a noob with testing tools. Do you have any example on how to use this with a none-typescript projet while using both [mocha](https://mochajs.org/) and [webextension-polyfill](https://github.com/mozilla/webextension-polyfill).

Thanks a lot 🙏

**Comment by Lusito** [comment]
You can use [webextension-polyfill-ts](https://github.com/lusito/forget-me-not) with javascript projects as well. It enhances your javascript experience if you have an Editor like [vscode](https://code.visualstudio.com/), which is able to read the type definitions.

So there is no hard reason to use webextension-polyfill for javascript projects.

Regarding mocha though, I'm afraid I can't give you anything. mockzilla is build upon jest. Can't use it without. Or maybe you can, but only with hacks and you won't get the best experience from it.

I switched my web-extension and some other projects from mocha to jest. While it does cause some work, I think it was worth the effort.

**Comment by NicolasWanteeed** [comment]
Thank you for the quick response 🙏 I might give jest a try then 🙂
