### ISSUE TITLE
Event mocking within messaging

### ISSUE THREAD

**Issue by kabeleced77** [Lusito/mockzilla-webextension#13]
I'd like to test following piece of webextension code which registers two event handlers in a background script

    import browser from 'webextension-polyfill'

    browser.runtime.onConnect.addListener((port: browser.Runtime.Port) => {
      port.onMessage.addListener((message: any) => {
        // do something
        port.postMessage(`reply`)
      })
    })

The event handlers are
1. Listen for connections (e.g. from content script) using `browser.runtime.onConnect.addListener`
2. Listen for messages sent (e.g. by content script )using `port.onMessage.addListener`

I can mock and emit first event using `mockzilla-webextension`:

    import 'mockzilla-webextension'
    import { mockEvent, MockzillaEventOf } from 'mockzilla-webextension'
    
    describe('messaging event mocking', () => {
      let addListenerOnConnect: MockzillaEventOf<typeof mockBrowser.runtime>
    
      beforeEach(() => {
        addListenerOnConnect = mockEvent(mockBrowser.runtime.onConnect)
      })
    
      describe('function test', () => {
        it('handle received message', () => {
          // call system-under-test
          // ...
    
          // sent message to be handled by system-under-test
          addListenerOnConnect.emit('message')
        })
      })
    })
    
Reaching the code of the second event handler I get a type error:

    TypeError: Cannot read property 'addListener' of undefined`:

      13 |     browser.runtime.onConnect.addListener((port: browser.Runtime.Port) => {
    > 14 |       port.onMessage.addListener((message: any) => {
         |                      ^

I'm not able to mock this event using the same technique above. I'd happy about some help. Thanks in advance.

**Comment by Lusito** [comment]
Hi, you have two issues here:

First, the type of the event 
```ts
    let addListenerOnConnect: MockzillaEventOf<typeof mockBrowser.runtime>; // should be typeof mockBrowser.runtime.onConnect
```
This causes the type of the event to be `(...args: any[]) => void`.
I'll have to look into this. Maybe this should be of type never or unknown instead to make typescript complain more.

The second problem is a bit hidden due to the fact, that the first problem is there (once you change the code above, you'll see typescript complain):

```ts
// here you should emit the type of event, that your event listener expects.
// I.e. the value you pass must be of type browser.Runtime.Port, not a string like you did here:
addListenerOnConnect.emit('message')

// The mockzilla way would be to provide a deep mock like this:
const [port, mockPort] = deepMock<browser.Runtime.Port>("port");
mockPort.onMessage.addListener.expect(...); // configure your expectations/spies, etc.
addListenerOnConnect.emit(port);
```

**Comment by kabeleced77** [comment]
Thanks for clarifying this.
First issue has been solved as suggested.
Second issue I tried as suggested but now I get another problem using deep mock:

    test/Messaging.test.ts:40:41 - error TS2503: Cannot find namespace 'browser'.

    40       const [port, mockPort] = deepMock<browser.Runtime.Port>("port")
                                               ~~~~~~~

Where do I get the `browser` object from? And, I'm always confused with lower case `browser` and upper case `Browser` -what's the difference, if any? Thank you.

**Comment by kabeleced77** [comment]
It went better when I changed it to the namespace `Browser` (upper case) and added following import:

     import Browser from 'webextension-polyfill'

**Comment by Lusito** [comment]
browser is the default export, so you get it like this
```ts
import browser, { /* any non-default imports*/ } from "webextension-polyfill";
```

`Browser` Is only a namespace, while `browser` is both a variable and a namespace (`Browser`). 

If you want to use the type, you should be able to use both.. you just need to make sure you imported it. If you want to make things even shorter, you can just import Runtime directly:

```ts
import { Runtime } from "webextension-polyfill";

const [port, mockPort] = deepMock<Runtime.Port>("port");
```

The only reason I used the `browser.Runtime.Port` version is because you used it yourself:
```ts
browser.runtime.onConnect.addListener((port: browser.Runtime.Port) => {...});
```

FYI: types are already on the definition of addListener, so you can remove the manual type definition without losing the type-safety:
```ts
browser.runtime.onConnect.addListener((port) => {...});
```

**Comment by Lusito** [comment]
Just noticed this:

```ts
import Browser from 'webextension-polyfill'
```

In this case, Browser is variable + namespace version, since you imported the "default export" and named it "Browser".
If you want the namespace version, please import it like this:

```ts
import { Browser } from 'webextension-polyfill'
```
And if you want the variable version, please import it in lowercase to avoid confusion:

```ts
import browser from 'webextension-polyfill'
```

**Comment by kabeleced77** [comment]
I changed it to      

      import browser from 'webextension-polyfill'

      const [port, mockPort] = deepMock<browser.Runtime.Port>('port')

and it works (too). Thanks.

**Comment by kabeleced77** [comment]
For completeness: my test setup looks now like this where I can emit first a connection request and second a sent message. Both are handled in the system-under-test as listed in my initial post:

        import { deepMock } from 'mockzilla'
        import { mockEvent, MockzillaEventOf } from 'mockzilla-webextension'
        import { Runtime } from 'webextension-polyfill'
        
        describe('messaging event mocking', () => {
          const [port, mockPort] = deepMock<Runtime.Port>('port')
          let addListenerOnConnect: MockzillaEventOf<typeof mockBrowser.runtime.onConnect>
          let addListenerOnMessage: MockzillaEventOf<typeof mockPort.onMessage>
        
          beforeEach(() => {
            addListenerOnConnect = mockEvent(mockBrowser.runtime.onConnect)
            addListenerOnMessage = mockEvent(mockPort.onMessage)
          })
        
          describe('function test', () => {
            it('handle received message', () => {
              // call system-under-test
              // ...
        
			  // mock port.postMessage()
              mockPort.postMessage.expect('message').andReturn()
			  // connection request to be handled by system-under-test
              addListenerOnConnect.emit(port)
              // sent message to be handled by system-under-test
              addListenerOnMessage.emit('message', port)
            })
          })
        })
        
Thank you for your quick support.
