### ISSUE TITLE
Error: Mock "browser.default" is not implemented

### ISSUE THREAD

**Issue by lmk123** [Lusito/mockzilla-webextension#7]
Hi, thank you so much for creating such a great project!

I used it in my own project, but ran into an error: `Error: Mock "browser.default" is not implemented`

## Steps to reproduce

First, I followed the documentation and installed:
  - `webextension-polyfill` 0.8.0
  - `@types/webextension-polyfill` 0.8.0
  - `jest` 27.0.6
  - `ts-jest` 27.0.4
  - `@types/jest` 26.0.24
  - `mockzilla` 0.11.2
  - `mockzilla-webextension` 0.12.0

Then I set up `setupFilesAfterEnv`.

Everything is ready, when I test the following code：

```js
import browser from 'webextension-polyfill'
export async function test() {
  return await browser.storage.local.get({ test: 'jest' })
}
```

The console reported an error：`Error: Mock "browser.default" is not implemented`

## Solution

https://github.com/Lusito/mockzilla-webextension/blob/6504c26abdfdd4f7bf6248a97309a26540aab774/src/mockBrowser.ts#L32

I changed this to `jest.mock("webextension-polyfill", () => ({default: proxy}));`, then the test works fine.

I think it is related to: https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options

**Comment by Lusito** [comment]
webextension-polyfill is not an ES module; there is no default export; it’s a UMD module that assigns to module.exports if available. 
It's probably an issue with your code-setup. Have you set up [tsconfig#esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop)? (if you are using typescript)

**Comment by lmk123** [comment]
You're right, I didn't set this option, thanks!
