### ISSUE TITLE
Mock "browser.tabs" is not implemented

### ISSUE THREAD

**Issue by lmk123** [Lusito/mockzilla-webextension#9]
The preparation is the same as #7, and I changed `jest.mock("webextension-polyfill", () => proxy)` to `jest.mock("webextension-polyfill", () => ({ default: proxy }))`.

When I test the following code:

```js
import browser from 'webextension-polyfill'

browser.tabs.onDetached.addListener((tabId, detachInfo) => {
  console.log(tabId, detachInfo)
})
```

The console reported an error: `Mock "browser.tabs" is not implemented`

But if I wrap `browser.tabs` in `setTimeout`, I don't have this problem:

```js
import browser from 'webextension-polyfill'

setTimeout(() => {
  browser.tabs.onDetached.addListener((tabId, detachInfo) => {
    console.log(tabId, detachInfo)
  })
})
```

**Comment by Lusito** [comment]
Please follow the tutorials: https://lusito.github.io/mockzilla-webextension/browser.html#solution

The things you need to do:
1. Set up mockzilla-webextension properly
2. Prepare your test by using `mockBrowser` to expect calls or mock values.
3. Call your own logic.

If you don't do the preparation step, you will get errors.

**Comment by lmk123** [comment]
After I added `tsconfig#esModuleInterop`, everything is fine now. Thank you for your reply.
